name: "SonarQube Scan Action"
description: "Run SonarQube scan"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Generate coverage
      shell: bash
      run: npm test -- --coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6